"""
SQLAlchemy ORM models.

Defines the `Student` table, replacing the flat `students.json`
structure used in the original CLI project (Task 04).
"""

from sqlalchemy import Column, Integer, String
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class Student(Base):
    """Database representation of a student record."""

    __tablename__ = "students"

   # Auto-incrementing primary key generated by the database.
   # Each student receives a unique ID automatically.
    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    name: Mapped[str] = mapped_column(String, nullable=False)
    age: Mapped[int] = mapped_column(Integer, nullable=False)
    grade: Mapped[str] = mapped_column(String, nullable=False)
    email: Mapped[str] = mapped_column(String, nullable=False, unique=True)

    def __repr__(self) -> str:
        return f"Student(id={self.id!r}, name={self.name!r})"
